### ISSUE TITLE
getting Multiplattform Compose to work

### ISSUE THREAD

**Issue by MrHemanik** [choffmann/budget-binder#4]

**Comment by akatranlp** [comment]
jvmMain is its own application and we get own binaries for macOS, Linux and Windows.

**Comment by choffmann** [comment]
Binaries for `macOS`, `Linux` and `Windows` are managed by Compose Desktop. 
See https://github.com/JetBrains/compose-jb/blob/master/tutorials/Native_distributions_and_local_execution/README.md
