### ISSUE TITLE
HiFi - Implement Welcome Screen

### ISSUE THREAD

**Issue by choffmann** [choffmann/budget-binder#52]
A Welcome Screen should be implemented to introduce the user to the App.

**Suggestions for Views**
- First View (Welcome to Budget Binder)
  -> what is Budget Binder?
- Second View (How you can save your money)
  -> show the user, how he can save money with our app
- Last View (Let's get started)
  -> here the user can register a account or login

**Comment by MrHemanik** [comment]
@choffmann the hamburger menu on the welcome screen shows dummy logged-in data, don't we want only to show "dark mode" in the menu?
[Opened Hamburger Menu With Logged-In Data when not logged in](https://i.imgur.com/8jPFRjF.png)
